### PR TITLE
Sends confirmation email for student applications

### LINKED ISSUE #128: Confirmation email not sent for student applications

### PR DESCRIPTION
**Pull request by lilshim**
Fix #128

### CODE REVIEW

**Comment by lilshim** [comment]
Woops I didn't check Guard before pushing. My b

**Comment by SamLau95** [comment]
Can I ping you on this? :)

**Comment by chenhoward** [comment]
@lilshim ^^

**Comment by lilshim** [comment]
@SamLau95 I just worked through this with @chenhoward. Tested on dev and email works great.

**Comment by lilshim** [comment]
Fixing codeship failures rn

**Comment by lilshim** [comment]
Swaggie swag pullme in brothas @SamLau95 @chenhoward

**Pull request merged**
