### PR TITLE
Calendly Field + Confirmation Email

### PR DESCRIPTION
**Pull request by aivantg**
Added a new field for signing up for Calendly and added a confirmation email after submitting interest form (copy is tbd)

image

### CODE REVIEW

**Comment by kwfk** [comment]
@aivantg what do think about embedding the calendly? they provide an embed script so its just a matter of copy and paste. might help with the user flow cause then they don't have to leave the page

**Comment by aivantg** [comment]
@kwfk that sounds kinda lit LOL, i'm gonna look into it

**Comment by aivantg** [comment]
@adowski what do you think about Fred's idea? Embedding Calendly directly on the app

**Comment by kwfk** [comment]
Oh it's already merged into staging #369

**Comment by aivantg** [comment]
o fuq nice!

**Pull request merged**
