### PR TITLE
Change student apply image

### PR DESCRIPTION
**Pull request by vivekraghuram**
This just changes the photo used on the apply and student apply pages for students. It also adds a little space under the alumni section title. 

applypage
studentapply

### CODE REVIEW

**Comment by SamLau95** [comment]
Looks good! Feel free to merge once `rspec` passes.

**Comment by vivekraghuram** [comment]
@SamLau95 can you give me codeship access? I can't actually see it...

**Comment by SamLau95** [comment]
What's your email?

You should be able to see what happened locally by running `rpsec` (and `guard` will let you know immediately when tests fail). It looks like it's a scss linting error.

**Comment by vivekraghuram** [comment]
@SamLau95 the test if failing for me on master. It's not a problem with my branch.

**Comment by SamLau95** [comment]
What does `scss-lint -c .scss-lint.yml` output? Are those fixable? If it's easy then I think we can just fix it, but if not then lmk and I'll just merge it.

**Comment by vivekraghuram** [comment]
That's weird. I don't get the failure if I run all the rspec tests on master. Anyway fixed the issue. It was just an ordering css issue

**Comment by SamLau95** [comment]
Thanks! :)

**Pull request merged**
